name: proclaim
description: "A daily Bible reading app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  excel: ^4.0.3
  intl: ^0.19.0
  http: ^1.2.0
  path_provider: ^2.1.0
  cupertino_icons: ^1.0.8
  csv: ^6.0.0

  # ⭐ Google Drive API 추가
  googleapis: ^11.0.0
  googleapis_auth: ^1.6.0
  gsheets: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Proclaim.xlsx
    - assets/bible.json
    - assets/bible_esv.json
    - assets/images/shofar_logo.png